on:
  - push
  - pull_request

jobs:
  arduino-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
          - station-revamp